name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Change if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/ky/thesis_PLC
            git pull origin master
