name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Pull latest code and deploy
        run: |
          cd /home/ky/thesis_PLC
          git pull
          
