name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to raspberry Pi via pagekite
        uses: actions/checkout@v3

      - name: Deploy to Raspberry Pi via Serveo
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ky.pagekite.me
          port: 22
          username: ky 
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /home/ky/thesis_PLC
            git pull origin master
